"""100 seed questions for QuizSpark. Mix of general knowledge, tech, and business trivia."""

SEED_QUESTIONS = [
    ("What does HTTP stand for?", "HyperText Transfer Protocol", "High Transfer Text Protocol", "HyperTool Transfer Process", "Home Transfer Text Protocol", "A", "HTTP stands for HyperText Transfer Protocol — the foundation of data communication for the World Wide Web."),
    ("Which planet is known as the Red Planet?", "Venus", "Mars", "Jupiter", "Saturn", "B", "Mars is called the Red Planet because iron oxide (rust) on its surface gives it a reddish appearance."),
    ("Who painted the Mona Lisa?", "Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet", "C", "Leonardo da Vinci painted the Mona Lisa between 1503 and 1519. It hangs in the Louvre, Paris."),
    ("What is the largest ocean on Earth?", "Atlantic", "Indian", "Arctic", "Pacific", "D", "The Pacific Ocean is the largest and deepest of Earth's oceans, covering more than 60 million square miles."),
    ("Which language is primarily used for iOS app development?", "Kotlin", "Swift", "Java", "Ruby", "B", "Swift is Apple's modern programming language introduced in 2014, used for iOS, macOS, watchOS, and tvOS apps."),
    ("What year did World War II end?", "1943", "1944", "1945", "1946", "C", "World War II ended in 1945 with the surrender of Japan in September, following Germany's surrender in May."),
    ("Which company created the React JavaScript library?", "Google", "Meta (Facebook)", "Microsoft", "Twitter", "B", "React was created by Meta (formerly Facebook) and released as open source in 2013."),
    ("What is the chemical symbol for gold?", "Gd", "Go", "Au", "Ag", "C", "Au comes from the Latin word 'aurum', meaning gold. Ag is silver."),
    ("How many continents are there?", "5", "6", "7", "8", "C", "There are 7 continents: Africa, Antarctica, Asia, Australia, Europe, North America, and South America."),
    ("What is the capital of Japan?", "Beijing", "Seoul", "Tokyo", "Bangkok", "C", "Tokyo has been the capital of Japan since 1868 when it replaced Kyoto."),
    ("Which is the smallest prime number?", "0", "1", "2", "3", "C", "2 is the smallest and the only even prime number."),
    ("What does CPU stand for?", "Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processor Unifier", "A", "CPU stands for Central Processing Unit — the primary component that executes instructions in a computer."),
    ("Who wrote 'Romeo and Juliet'?", "Charles Dickens", "William Shakespeare", "Mark Twain", "Jane Austen", "B", "William Shakespeare wrote Romeo and Juliet, believed to have been penned between 1591 and 1595."),
    ("What is the largest mammal in the world?", "African Elephant", "Blue Whale", "Giraffe", "Polar Bear", "B", "The Blue Whale is the largest animal ever known to have lived, reaching lengths of 30 metres."),
    ("Which gas do plants absorb from the atmosphere?", "Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen", "C", "Plants absorb carbon dioxide (CO₂) during photosynthesis and release oxygen."),
    ("What is the currency of the United Kingdom?", "Euro", "Dollar", "Pound Sterling", "Franc", "C", "The Pound Sterling (GBP, £) is the official currency of the United Kingdom."),
    ("Which planet has the most moons?", "Jupiter", "Saturn", "Uranus", "Neptune", "B", "As of latest counts, Saturn has the most confirmed moons — over 140 — surpassing Jupiter."),
    ("What is 15% of 200?", "20", "25", "30", "35", "C", "15% of 200 = 0.15 × 200 = 30."),
    ("Which language has the most native speakers?", "English", "Hindi", "Spanish", "Mandarin Chinese", "D", "Mandarin Chinese has the largest number of native speakers, roughly 900 million."),
    ("What does SQL stand for?", "Structured Query Language", "Simple Question Logic", "System Query Line", "Sequential Query Language", "A", "SQL stands for Structured Query Language, used to manage and query relational databases."),
    ("Which is the tallest mountain in the world?", "K2", "Kangchenjunga", "Mount Everest", "Makalu", "C", "Mount Everest, at 8,848.86 metres, is the tallest mountain above sea level."),
    ("Who is known as the father of computers?", "Alan Turing", "Charles Babbage", "Bill Gates", "Steve Jobs", "B", "Charles Babbage is called the father of computers for designing the Analytical Engine in the 1830s."),
    ("What is the freezing point of water in Celsius?", "-10°C", "0°C", "32°C", "100°C", "B", "Water freezes at 0°C (32°F) at standard atmospheric pressure."),
    ("Which country is known as the Land of the Rising Sun?", "China", "South Korea", "Japan", "Thailand", "C", "Japan is called the Land of the Rising Sun because it lies at the eastern edge of Asia where the sun rises first."),
    ("What is the powerhouse of the cell?", "Nucleus", "Ribosome", "Mitochondria", "Chloroplast", "C", "Mitochondria are known as the powerhouse of the cell because they generate most of the cell's ATP energy."),
    ("Who invented the telephone?", "Thomas Edison", "Alexander Graham Bell", "Nikola Tesla", "Guglielmo Marconi", "B", "Alexander Graham Bell was awarded the first US patent for the invention of the telephone in 1876."),
    ("What is the largest desert in the world?", "Sahara", "Gobi", "Kalahari", "Antarctic", "D", "The Antarctic Desert is technically the world's largest desert by area, as deserts are defined by low precipitation."),
    ("How many bones are in the adult human body?", "196", "206", "216", "226", "B", "The adult human skeleton has 206 bones."),
    ("Which company makes the iPhone?", "Samsung", "Google", "Apple", "Nokia", "C", "Apple Inc. designs and manufactures the iPhone, first released in 2007."),
    ("What is the boiling point of water in Fahrenheit?", "180°F", "200°F", "212°F", "232°F", "C", "Water boils at 212°F (100°C) at standard atmospheric pressure."),
    ("Which is the longest river in the world?", "Amazon", "Nile", "Yangtze", "Mississippi", "B", "The Nile in Africa is traditionally regarded as the world's longest river at approximately 6,650 km."),
    ("What does 'www' stand for in a website URL?", "World Wide Web", "World Web Wide", "Web World Wide", "Wide World Web", "A", "WWW stands for World Wide Web — the information system of interlinked hypertext documents accessed via the Internet."),
    ("Who was the first President of the United States?", "Thomas Jefferson", "Abraham Lincoln", "George Washington", "John Adams", "C", "George Washington served as the first President of the United States from 1789 to 1797."),
    ("What is the hardest natural substance?", "Gold", "Iron", "Diamond", "Platinum", "C", "Diamond is the hardest known natural material, scoring 10 on the Mohs hardness scale."),
    ("Which social media platform was launched first?", "Instagram", "Facebook", "Twitter", "LinkedIn", "D", "LinkedIn launched in May 2003, before Facebook (2004), Twitter (2006), and Instagram (2010)."),
    ("What is the largest organ in the human body?", "Liver", "Brain", "Skin", "Heart", "C", "The skin is the largest organ, covering the entire external surface of the body."),
    ("Which country hosted the 2020 Summer Olympics?", "China", "Brazil", "Japan", "France", "C", "Japan hosted the 2020 Summer Olympics in Tokyo, held in 2021 due to COVID-19."),
    ("What is the speed of light in a vacuum?", "300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s", "A", "The speed of light in a vacuum is approximately 299,792 km/s, commonly rounded to 300,000 km/s."),
    ("Which programming language is Python named after?", "A snake", "Monty Python", "A scientist", "A city", "B", "Python was named after the British comedy group Monty Python, not the snake."),
    ("What is the smallest country in the world?", "Monaco", "Vatican City", "San Marino", "Liechtenstein", "B", "Vatican City is the smallest country in the world by both area (0.49 km²) and population."),
    ("Who painted the ceiling of the Sistine Chapel?", "Raphael", "Donatello", "Michelangelo", "Botticelli", "C", "Michelangelo painted the Sistine Chapel ceiling between 1508 and 1512."),
    ("Which vitamin is produced when skin is exposed to sunlight?", "Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D", "D", "Vitamin D is synthesised in the skin when exposed to UVB rays from sunlight."),
    ("What is the main ingredient in guacamole?", "Tomato", "Avocado", "Pepper", "Onion", "B", "Avocado is the primary ingredient in guacamole, an Aztec-origin dip."),
    ("Which is the fastest land animal?", "Lion", "Cheetah", "Horse", "Antelope", "B", "The cheetah is the fastest land animal, reaching speeds of up to 120 km/h (75 mph)."),
    ("What does 'AI' stand for?", "Automated Interface", "Artificial Intelligence", "Advanced Internet", "Applied Informatics", "B", "AI stands for Artificial Intelligence — machines simulating human intelligence."),
    ("What is the currency of Japan?", "Yuan", "Won", "Yen", "Rupee", "C", "The Japanese Yen (¥) is the official currency of Japan."),
    ("How many players are on a football (soccer) team on the field?", "9", "10", "11", "12", "C", "Each football (soccer) team fields 11 players including the goalkeeper."),
    ("Which planet is closest to the Sun?", "Venus", "Mercury", "Earth", "Mars", "B", "Mercury is the closest planet to the Sun in our solar system."),
    ("What is the capital of Australia?", "Sydney", "Melbourne", "Canberra", "Perth", "C", "Canberra is the capital of Australia, chosen as a compromise between Sydney and Melbourne."),
    ("Who wrote 'The Origin of Species'?", "Isaac Newton", "Charles Darwin", "Albert Einstein", "Galileo", "B", "Charles Darwin published 'On the Origin of Species' in 1859, presenting the theory of evolution by natural selection."),
    ("What is the term for a word that reads the same forwards and backwards?", "Anagram", "Palindrome", "Homonym", "Synonym", "B", "A palindrome reads the same forwards and backwards, like 'racecar' or 'level'."),
    ("Which is the largest country by land area?", "Canada", "China", "USA", "Russia", "D", "Russia is the largest country by area, spanning over 17 million square kilometres."),
    ("What does 'RAM' stand for in computers?", "Read Access Memory", "Random Access Memory", "Rapid Application Module", "Runtime Available Memory", "B", "RAM stands for Random Access Memory — temporary memory used by a computer while running."),
    ("Who developed the theory of relativity?", "Isaac Newton", "Nikola Tesla", "Albert Einstein", "Stephen Hawking", "C", "Albert Einstein developed the special (1905) and general (1915) theories of relativity."),
    ("What is the pH of pure water?", "5", "6", "7", "8", "C", "Pure water has a neutral pH of 7 at 25°C."),
    ("Which sea creature has three hearts?", "Shark", "Octopus", "Whale", "Dolphin", "B", "Octopuses have three hearts — two branchial and one systemic."),
    ("What is the national sport of Canada?", "Ice Hockey", "Lacrosse", "Baseball", "Football", "B", "Lacrosse is the official national summer sport, and ice hockey the national winter sport of Canada."),
    ("Which element has the atomic number 1?", "Helium", "Hydrogen", "Oxygen", "Carbon", "B", "Hydrogen has atomic number 1 — it has one proton in its nucleus."),
    ("What is the largest planet in our solar system?", "Saturn", "Neptune", "Jupiter", "Uranus", "C", "Jupiter is the largest planet in our solar system with a diameter of about 143,000 km."),
    ("Which musical instrument has 88 keys?", "Organ", "Piano", "Harpsichord", "Accordion", "B", "A standard modern piano has 88 keys — 52 white and 36 black."),
    ("Who invented the light bulb?", "Nikola Tesla", "Thomas Edison", "Benjamin Franklin", "Michael Faraday", "B", "Thomas Edison is credited with inventing the first commercially practical incandescent light bulb in 1879."),
    ("What is the capital of Canada?", "Toronto", "Vancouver", "Ottawa", "Montreal", "C", "Ottawa has been the capital of Canada since 1867."),
    ("Which ocean is between Africa and Australia?", "Pacific", "Atlantic", "Indian", "Arctic", "C", "The Indian Ocean lies between Africa and Australia."),
    ("What year did the Titanic sink?", "1910", "1912", "1914", "1916", "B", "The Titanic sank on 15 April 1912 after hitting an iceberg on its maiden voyage."),
    ("Which vitamin is also known as ascorbic acid?", "Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D", "C", "Vitamin C is chemically known as ascorbic acid and is essential for the growth and repair of tissues."),
    ("What is the longest bone in the human body?", "Tibia", "Femur", "Humerus", "Fibula", "B", "The femur (thigh bone) is the longest and strongest bone in the human body."),
    ("Which country invented paper?", "India", "Egypt", "China", "Greece", "C", "Paper was invented in China around 105 AD, traditionally attributed to Cai Lun."),
    ("What is the collective noun for a group of lions?", "Pack", "Herd", "Pride", "Flock", "C", "A group of lions is called a pride."),
    ("Which is the deepest point in the ocean?", "Java Trench", "Puerto Rico Trench", "Mariana Trench", "Tonga Trench", "C", "The Mariana Trench in the western Pacific reaches nearly 11,000 metres deep at Challenger Deep."),
    ("What is the largest species of bear?", "Grizzly Bear", "Polar Bear", "Black Bear", "Brown Bear", "B", "The polar bear is the largest species of bear and the largest land carnivore."),
    ("Who founded Microsoft?", "Steve Jobs", "Bill Gates and Paul Allen", "Larry Page", "Mark Zuckerberg", "B", "Microsoft was founded by Bill Gates and Paul Allen in 1975."),
    ("Which country has the most population?", "USA", "China", "India", "Indonesia", "C", "India surpassed China in 2023 to become the most populous country in the world."),
    ("What is the study of earthquakes called?", "Geology", "Seismology", "Volcanology", "Meteorology", "B", "Seismology is the scientific study of earthquakes and the propagation of elastic waves through the Earth."),
    ("What does 'GPS' stand for?", "General Positioning System", "Global Positioning System", "Geographic Point Service", "Guided Path System", "B", "GPS stands for Global Positioning System, a satellite-based navigation system."),
    ("Which is the smallest bone in the human body?", "Malleus", "Incus", "Stapes", "Radius", "C", "The stapes, located in the middle ear, is the smallest bone in the human body."),
    ("Who was the first person to walk on the Moon?", "Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins", "C", "Neil Armstrong became the first human to walk on the Moon on 20 July 1969 during Apollo 11."),
    ("What is the tallest building in the world?", "Shanghai Tower", "Burj Khalifa", "One World Trade Center", "Merdeka 118", "B", "The Burj Khalifa in Dubai stands at 828 metres and has been the world's tallest building since 2010."),
    ("Which continent is the driest?", "Africa", "Asia", "Australia", "Antarctica", "D", "Antarctica is the driest continent — most of it is a polar desert with very little precipitation."),
    ("What is the primary language of Brazil?", "Spanish", "Portuguese", "French", "English", "B", "Portuguese is the official and most widely spoken language in Brazil."),
    ("How many colors are in a rainbow?", "5", "6", "7", "8", "C", "A rainbow has 7 colours: red, orange, yellow, green, blue, indigo, violet (ROY G BIV)."),
    ("Which planet is known as the Morning Star?", "Mars", "Venus", "Mercury", "Jupiter", "B", "Venus is often called the Morning Star or Evening Star because it is visible near the Sun's rise or set."),
    ("What is the currency of the European Union (most member states)?", "Pound", "Dollar", "Euro", "Franc", "C", "The Euro (€) is the official currency of the Eurozone, used by 20 of 27 EU member states."),
    ("Who wrote 'Hamlet'?", "Christopher Marlowe", "William Shakespeare", "John Milton", "Ben Jonson", "B", "William Shakespeare wrote Hamlet, believed to have been composed between 1599 and 1601."),
    ("What does 'URL' stand for?", "Uniform Resource Locator", "Universal Reference Link", "Unified Route Language", "User Redirect Line", "A", "URL stands for Uniform Resource Locator — the address of a resource on the internet."),
    ("Which vitamin helps blood clotting?", "Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K", "D", "Vitamin K plays a crucial role in blood coagulation."),
    ("What is the largest island in the world?", "Australia", "Greenland", "Madagascar", "Borneo", "B", "Greenland is the world's largest island. Australia is classified as a continent, not an island."),
    ("Who is credited with inventing the World Wide Web?", "Steve Jobs", "Tim Berners-Lee", "Larry Page", "Vint Cerf", "B", "Tim Berners-Lee invented the World Wide Web in 1989 while at CERN."),
    ("Which mineral is essential for strong bones and teeth?", "Iron", "Calcium", "Potassium", "Sodium", "B", "Calcium is essential for the development and maintenance of strong bones and teeth."),
    ("What is the primary gas in Earth's atmosphere?", "Oxygen", "Carbon Dioxide", "Nitrogen", "Argon", "C", "Nitrogen makes up about 78% of Earth's atmosphere; oxygen is about 21%."),
    ("Which artist is famous for cutting off part of his own ear?", "Claude Monet", "Vincent van Gogh", "Pablo Picasso", "Salvador Dalí", "B", "Vincent van Gogh famously severed part of his left ear in December 1888."),
    ("What is the fastest bird in the world?", "Golden Eagle", "Peregrine Falcon", "Ostrich", "Swift", "B", "The Peregrine Falcon can reach diving speeds over 320 km/h, making it the fastest animal on Earth."),
    ("Which country gifted the Statue of Liberty to the USA?", "Britain", "Germany", "France", "Spain", "C", "France gifted the Statue of Liberty to the United States in 1886 to celebrate friendship and shared democratic ideals."),
    ("What is the largest fish in the world?", "Great White Shark", "Whale Shark", "Blue Marlin", "Manta Ray", "B", "The Whale Shark is the largest fish, reaching up to 18 metres in length. Whales are mammals, not fish."),
    ("Which programming language is known as the 'mother of all languages'?", "C", "Assembly", "FORTRAN", "BASIC", "A", "The C programming language is often called the mother of all modern languages due to its influence."),
    ("What is the study of the human mind called?", "Sociology", "Anthropology", "Psychology", "Philosophy", "C", "Psychology is the scientific study of the mind and behaviour."),
    ("Which is the only mammal that can truly fly?", "Flying Squirrel", "Bat", "Sugar Glider", "Colugo", "B", "Bats are the only mammals capable of true, sustained flight. Others only glide."),
    ("What is the chemical formula for table salt?", "H2O", "NaCl", "CO2", "KCl", "B", "NaCl (sodium chloride) is the chemical formula for common table salt."),
    ("Who directed the movie 'Titanic' (1997)?", "Steven Spielberg", "James Cameron", "Christopher Nolan", "George Lucas", "B", "James Cameron directed the 1997 blockbuster Titanic, which won 11 Academy Awards."),
    ("What is the largest rainforest in the world?", "Congo Rainforest", "Amazon Rainforest", "Daintree Rainforest", "Valdivian Rainforest", "B", "The Amazon Rainforest in South America is the largest tropical rainforest in the world."),
    ("Which app is known for disappearing messages?", "WhatsApp", "Snapchat", "Telegram", "Signal", "B", "Snapchat, launched in 2011, popularised the concept of disappearing messages and photos."),
    ("What is the tallest waterfall in the world?", "Niagara Falls", "Angel Falls", "Victoria Falls", "Iguazu Falls", "B", "Angel Falls in Venezuela is the world's tallest uninterrupted waterfall at 979 metres."),
    ("Which company owns YouTube?", "Meta", "Microsoft", "Google (Alphabet)", "Amazon", "C", "Google acquired YouTube in 2006 for $1.65 billion. Google is now a subsidiary of Alphabet Inc."),
]
